#!/bin/bash


# 1.获取token
# 获取token文档：https://blog.cloudflare.com/zh-cn/api-tokens-general-availability-zh-cn

# 脚本来源于：https://blog.quzei.com/archives/cEPs1PFY
# 2026-2-26进行改版


# 检查参数
if [ 1 -ge "$#" ]; then
    echo "使用方法: <域名> <TOKEN> [<mac/IPV6后缀/wan口>]"
    echo "示例1: df.abc.xyz dkkdjkfdjkdaa"
    echo "示例2: df.abc.xyz dkkdjkfdjkdaa 64:db:8b:4d:7a5:55"
    echo "示例3: df.abc.xyz dkkdjkfdjkdaa 566f:24c1:f13:fa71"
    echo "示例4: df.abc.xyz dkkdjkfdjkdaa :1"
    echo "示例5: df.abc.xyz dkkdjkfdjkdaa wan"
    exit 1
fi

ddns=$1
CF_API_TOKEN=$2
SUFFIX=$3
RECORD_TYPE=AAAA
NEW_VALUE=ip

LOG_() {
    logger -t "【运行cloudflare_IPV6_ddns脚本】" "$1"
echo -e "\033[36;1m【$(TZ=UTC-8 date -R +%Y年%m月%d月\ %X)】 : \033[0m\033[35;1m$1 \033[0m"
}

[ ! -d "/tmp/log" ] && mkdir "/tmp/log"
IPV6LOG="/tmp/log/[${ddns}].log"



SUBDOMAIN=$(echo "${ddns}" | cut -d . -f 1)
DOMAIN=$(echo "${ddns}" | cut -d . -f 2-5)

LINE=1
[ "$3" = "wan" ] && LINE=2
ip=$(ip -6 a |grep 'scope global'|grep -v temporary|grep -v deprecated |grep -v ' fd' |grep -v /128 | awk -F '/|inet6 ' 'NR=='"${LINE}"'{print $2;}')




# IPV6前缀
PREFIX=$(echo $ip | cut -d: -f1-4)

if [ -z "${PREFIX}" ] ; then

LOG_ "[${ddns}] 获取IPV6错误！"
exit 1
fi

SUF_FIX=`echo ${SUFFIX} | tr A-Z a-z | tr - :`

#a=`echo ${SUF_FIX} | grep -oE '[a-f0-9]{1,4}(:[a-f0-9]{1,4}){3}|[a-f0-9]{1,4}(:[a-f0-9]{1,4}){0,3}::[a-f0-9]{0,4}(:[a-f0-9]{1,4}){0,3}'`
a=$(echo ${SUF_FIX} | grep -oE '[a-f0-9]{1,4}(:[a-f0-9]{1,4}){3}|[a-f0-9]{1,4}(:[a-f0-9]{1,4}){0,3}::[a-f0-9]{0,4}(:[a-f0-9]{1,4}){0,3}|[a-f0-9]{0,4}(:[a-f0-9]{1,4}){0,3}')
b=$(echo ${SUF_FIX} | grep -oE '[a-f0-9]{1,2}(:[a-f0-9]{1,2}){5}')

if [ "${SUFFIX}" = "wan" ] ; then
IPV6=$ip
else
if [ -z "${SUF_FIX}" ] ; then
IPV6=$ip
elif [ "${a}" == "${SUF_FIX}" ] ; then
IPV6="${PREFIX}:${SUF_FIX}"
elif [ "${b}" == "${SUF_FIX}" ] ; then

IPV6_NEI=$(ip -6 nei |grep ${SUF_FIX} |grep -oE '[a-f0-9]{1,4}(:[a-f0-9]{1,4}){7}|[a-f0-9]{1,4}(:[a-f0-9]{1,4}){0,7}::[a-f0-9]{0,4}(:[a-f0-9]{1,4}){0,7}'|grep ^2) 
	if [ -z "${IPV6_NEI}" ] ; then
		LOG_ "未找到与“$SUF_FIX”MAC地址对应的IPV6地址"
		exit 1
	else
		IPV6="${IPV6_NEI}"
	fi
else

	LOG_ "请优先输入正确的固定后缀，无固定后缀请输入设备的MAC地址，本机可以不输入！"
exit 1
fi
fi
##如果第三个参数为空时，为路由器自身的IPV6后缀，否则是设备的IPV6。

if [ -f "${IPV6LOG}" ] ; then
OLDIPV6=$(tail -n 1 "${IPV6LOG}")
else
OLDIPV6="::"
fi

if [ "${IPV6}" = "$OLDIPV6" ] ; then
LOG_ "[${ddns}] IPV6无变化！"
exit 0
fi

####################################################################
RETRY='--retry 3 --retry-delay 2 --retry-max-time 10 -ks'


# 获取 Zone ID
zone_response=$(curl ${RETRY} -X GET "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" \
     -H "Authorization: Bearer $CF_API_TOKEN" \
     -H "Content-Type: application/json")

#ZONE_ID=$(echo $zone_response | jq -r '.result[0].id')
ZONE_ID=$(echo "${zone_response}" | sed -e "s/ //g" |grep -o "id\":\"[0-9a-z]*\",\"name\":\"${DOMAIN}\",\"status\""|grep -o "id\":\"[0-9a-z]*\""| awk -F : '{print $2}'|grep -o "[a-z0-9]*")

if [ -z "$ZONE_ID" ]; then
    LOG_ "获取域名 Zone ID 失败: $DOMAIN，请检查你的token区域权限"
    exit 1
fi

# 获取 DNS 记录 ID
record_response=$(curl ${RETRY} -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?name=$SUBDOMAIN.$DOMAIN" \
     -H "Authorization: Bearer $CF_API_TOKEN" \
     -H "Content-Type: application/json")

#RECORD_ID=$(echo ${record_response} | jq -r '.result[0].id')
RECORD_ID=$(echo "${record_response}" | sed -e "s/ //g" | sed -e "s/"'"ttl":'"/"' \n '"/g" | grep "type\":\"${RECORD_TYPE}\"" | grep ",\"name\":\"${SUBDOMAIN}.${DOMAIN}\"" | grep -o "\"id\":\"[0-9a-z]\{32,\}\",\"" | awk -F : '{print $2}'|grep -o "[a-z0-9]*")

# 如果记录不存在则创建新的记录
if [ -z "$RECORD_ID" ] || [ "$RECORD_ID" == "null" ]; then
    LOG_ "DNS 记录不存在，创建新的记录..."
    response=$(curl ${RETRY} -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
         -H "Authorization: Bearer $CF_API_TOKEN" \
         -H "Content-Type: application/json" \
         --data '{
           "type": "'"$RECORD_TYPE"'",
           "name": "'"$SUBDOMAIN.$DOMAIN"'",
           "content": "'"${IPV6}"'",
           "ttl": 600,
           "proxied": false
         }')
else
    LOG_ "DNS 记录存在，更新记录..."
    response=$(curl ${RETRY} -X PUT "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$RECORD_ID" \
         -H "Authorization: Bearer $CF_API_TOKEN" \
         -H "Content-Type: application/json" \
         --data '{
           "type": "'"$RECORD_TYPE"'",
           "name": "'"$SUBDOMAIN.$DOMAIN"'",
           "content": "'"${IPV6}"'",
           "ttl": 600,
           "proxied": false
         }')
fi

# 检查操作是否成功
if echo "$response" | grep -q '"success":true'; then
    LOG_ "DNS 记录操作成功。"
    echo >> "${IPV6LOG}"
    echo  "[$(date +%F' '%X)] IPV6地址更新——>" >> "${IPV6LOG}"
    echo "${IPV6}" >> "${IPV6LOG}"
    
else
    LOG_ "DNS 记录操作失败。"
    LOG_ "响应: $response"
fi
